### ISSUE TITLE
Issue with Node AD

### ISSUE THREAD

**Issue by Uname-nikunj** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#11]
Hi

I am facing same issue can you please guide on same.

    throw new TypeError(`Invalid value for ${item}.${checker.error}`);
      ^

TypeError: Invalid value for redirectUrl.The URL must be valid and be https://
    at Object.keys.forEach (C:\Nikunj Data\Project\Active Directory\WebApp-OpenIDConnect-NodeJS-skeleton\node_modules\passport-azure-ad\lib\validator.js:51:13)
    at Array.forEach (native)
    at Validator.validate (C:\Nikunj Data\Project\Active Directory\WebApp-OpenIDConnect-NodeJS-skeleton\node_modules\passport-azure-ad\lib\validator.js:37:28)
    at new Strategy (C:\Nikunj Data\Project\Active Directory\WebApp-OpenIDConnect-NodeJS-skeleton\node_modules\passport-azure-ad\lib\oidcstrategy.js:495:13)
    at Object.<anonymous> (C:\Nikunj Data\Project\Active Directory\WebApp-OpenIDConnect-NodeJS-skeleton\app.js:42:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

Regards
Nikunj

**Comment by lovemaths** [comment]
@Uname-nikunj In your config.js, please set `allowHttpForRedirectUrl` option to true. This should solve the issue.

**Comment by lucashuet93** [comment]
@lovemaths I'm using the tutorial provided by the docs -https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-openidconnect-nodejs
Adding the allowHttpForRedirectUrl property does not fix the issue in the repo provided.

**Comment by lovemaths** [comment]
@lucashuet93 The tutorial is for passport-azure-ad version 1.x.x (current version is 3.x.x), it seems we haven't updated it. We will update it as soon as possible. Please download the `master` branch of this repo, and change the following parameters in `config.js`:

* `identityMetadata`

* `clientID`

* `redirectUrl` : make sure add 'http://localhost:3000/auth/openid/return' to your application reply url list in AAD protal

* `clientSecret` : this is the `key` you created for your application in AAD portal

Leave the rest parameters as it is.

Then set `exports.useMongoDBSessionStore ` to `false`. Now you should be able to run it. Let me know if there are still issues. Thank you.

**Comment by navyasric** [comment]
Closing this issue as it seems to be resolved by above comment. Also the current master branch of sample Readme has been updated.

**Comment by deshnpra** [comment]
I have same issue as below 

{"name":"AzureAD: OIDC Passport Strategy","hostname":"testpod45566","pid":32,"level":40,"msg":"Production environments should always validate the issuer.","time":"2020-09-13T18:28:58.428Z","v":0}
(node:32) UnhandledPromiseRejectionWarning: TypeError: Invalid value for clientID.The value cannot be empty
    at /app/frontend/node_modules/passport-azure-ad/lib/validator.js:51:13
    at Array.forEach (<anonymous>)
    at Validator.validate (/app/frontend/node_modules/passport-azure-ad/lib/validator.js:37:28)
    at new Strategy (/app/frontend/node_modules/passport-azure-ad/lib/oidcstrategy.js:520:13)
    at Object.<anonymous> (/app/frontend/server/passport.ts:86:14)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (/app/frontend/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (/app/frontend/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
